name: velik
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hexcolor: 3.0.1
  flutter_svg: 2.0.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: 2.3.2
  intl: 0.19.0
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  fonts:
    - family: m_plus
      fonts:
        - asset: lib/utils/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.TTF
    - family: m_plus_extra
      fonts:
        - asset: lib/utils/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.TTF
  assets:
    - assets/images/
    - assets/svg/


